### ISSUE TITLE
index.js - Variable not used

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#11]
https://github.com/trust2065/orchard/blob/fa86e2e1ed8194d0897ee7e8eee93ad48736457b/src/index.js#L7

**Comment by josephj** [comment]
Should be avoidable if you installed the ESLint VSCode plugin

**Comment by trust2065** [comment]
I do have linter installed, but sometimes it will still unfix if I didn't notice linter's notification.
To prevent it, I install eslinter and pre-commit, which will reject commit when problem exist.
