### ISSUE TITLE
fullPage.js License issue

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#27]
![image](https://user-images.githubusercontent.com/136648/61988163-2ff57b00-b050-11e9-998c-b6510eecab79.png)

https://alvarotrigo.com/fullPage/pricing/

Please remove the warning. It's not allowed since we need a *production-ready* page.

**Comment by trust2065** [comment]
I will remove it since no response from them.

**Comment by josephj** [comment]
That's fine. Just keep in mind there is a requirement for interactivity/animation. 

> As with any modern web-build we expect a level of interactivity/animation to be displayed on the nodes.

You can remove fullPage.js in this ticket, but please create another ticket to tackle the interactivity/animation thing.

**Comment by trust2065** [comment]
need to remove it make some other animation/interactivity
