### ISSUE TITLE
About `text-uppercase`

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#29]
When you have `text-uppercase`, the text inside should be a normal form.

**Bad**
```
<h1 class="text-uppercase">ANSWER YOUR BODY'S NEEDS</h1>
```

**Good**
```
<h1 class="text-uppercase">Answer your body's needs</h1>
```

Please scan thru your HTML and  fix this

**Comment by trust2065** [comment]
Do you think this is worth an independent commit?
I am a bit hesitate for many mini-commit... 
Sorry I just keep worry something which don't really have answer..

**Comment by josephj** [comment]
Definitely worthy for me. How can you fix a typo without a commit? 

Or maybe you have an existing branch which is related to this. Just fix it in that branch then. 

Doing a squash before merging is much more worthy than worrying if a commit is too small.
