### ISSUE TITLE
Not implementing according to provided design

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#5]
![Screen Shot 2019-07-10 at 8 21 17 am](https://user-images.githubusercontent.com/136648/60927080-ea188300-a2eb-11e9-9974-651ea8e60b0c.png)

**Comment by trust2065** [comment]
Need to find a way to keep horizontal space between images the same with vertical space between images.
![image](https://user-images.githubusercontent.com/13488449/61506392-40d93780-aa25-11e9-9834-a6ee9c9abf11.png)

**Comment by trust2065** [comment]
The way I found is **align those images center** then give the same padding.
